@LoginAPIServer_HostAddress = http://localhost:5073

POST {{LoginAPIServer_HostAddress}}/LoginAccount
Content-Type: application/json

{
    "UserID": "testId123@gmail.com",
    "Password": "testpassword12"
}
###

POST {{LoginAPIServer_HostAddress}}/CreateAccount
Content-Type: application/json

{
    "UserID": "testId123@gmail.com",
    "Password": "testpassword12"
}
###


// change body before test
POST {{LoginAPIServer_HostAddress}}/VerifyToken
Content-Type: application/json

{
    "PlayerId": 29,
    "Token":"624b60c58c9d8bfb6ff1886c2fd605d2adeb6ea4da576068201b6c6958ce93f4" 
}
